### ISSUE TITLE
Add ESLint and Prettier

### ISSUE THREAD

**Issue by jpelhaW** [ag-gipp/NLP-Land-frontend#3]
**Is your feature request related to a problem? Please describe.**
We need to lint the code for code quality and consistency.

**Describe the solution you'd like**
Include the solution from [this link](https://www.imaginarycloud.com/blog/how-to-configure-eslint-prettier-in-react/).

**Describe alternatives you've considered**
Other linting solutions are welcome.

**Comment by trannel** [comment]
Added in #26
